runtime: python
env: standard
entrypoint: gunicorn app:app --bind 0.0.0.0:$PORT

runtime_config:
  python_version: 3

basic_scaling:
  instances: 1
  idle_timeout: 5m
resources:
  cpu: 1
  memory_gb: 0.05
  disk_size_gb: .5
  instance_class: F1
